# version: 1.0.0
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
continuation_prompt = "[▸▹ ](bold bright-magenta)"

format = """($nix_shell$container$fill$git_metrics\n)$cmd_duration\
$hostname\
$localip\
$shlvl\
$shell\
$env_var\
$jobs\
$sudo\
$username\
$character"""

right_format = """
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cpp\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$fortran\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$xmake\
$zig\
$buf\
$conda\
$pixi\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$crystal\
$custom\
$status\
$os\
$battery\
$time"""

[fill]
symbol = ' '

[character]
format = "$symbol "
success_symbol = "[◎](bold italic bright-magenta)"
error_symbol = "[○](italic bright-red)"
vimcmd_symbol = "[■](italic bold bright-cyan)"
vimcmd_replace_one_symbol = "[◌](bold yellow)"
vimcmd_replace_symbol = "[□](bold yellow)"
vimcmd_visual_symbol = "[▼](bold bright-blue)"

[env_var.VIMSHELL]
format = "[$env_value]($style)"
style = 'bold italic bright-cyan'

[sudo]
format = "[$symbol]($style)"
style = "bold italic bright-purple"
symbol = "⋈┈"
disabled = false

[username]
style_user = "bold italic bright-magenta"
style_root = "bold italic bright-red"
format = "[⭘ $user]($style) "
disabled = false
show_always = false

[directory]
home_symbol = "⌂"
truncation_length = 2
truncation_symbol = "□ "
read_only = " ◈"
use_os_path_sep = true
style = "bold italic bright-cyan"
format = '[$path]($style)[$read_only]($read_only_style)'
repo_root_style = 'bold bright-magenta'
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) [△](bold bright-magenta)'

[cmd_duration]
format = "[◄ $duration ](bold italic bright-purple)"
min_time = 500

[jobs]
format = "[$symbol$number]($style) "
style = "bold bright-cyan"
symbol = "[▶](bold italic bright-magenta)"

[localip]
ssh_only = true
format = " ◯[$localipv4](bold bright-magenta)"
disabled = false

[time]
disabled = false
format = "[ $time]($style)"
time_format = "%R"
utc_time_offset = "local"
style = "italic dimmed bright-purple"

[battery]
format = "[ $percentage $symbol]($style)"
full_symbol = "█"
charging_symbol = "[↑](italic bold green)"
discharging_symbol = "↓"
unknown_symbol = "░"
empty_symbol = "▃"

[[battery.display]]
threshold = 20
style = "italic bold red"

[[battery.display]]
threshold = 60
style = "italic bold bright-purple"

[[battery.display]]
threshold = 70
style = "italic bold bright-magenta"

[git_branch]
format = " [$branch(:$remote_branch)]($style)"
symbol = "[△](bold bright-magenta)"
style = "bold italic bright-cyan"
truncation_symbol = "⋯"
truncation_length = 11
ignore_branches = ["main", "master"]
only_attached = true

[git_metrics]
format = '([▴$added]($added_style))([▿$deleted]($deleted_style))'
added_style = 'bold italic green'
deleted_style = 'bold italic red'
ignore_submodules = true
disabled = false

[git_status]
style = "bold italic bright-magenta"
format = "([⎪$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed⎥]($style))"
conflicted = "[◪◦](bold bright-red)"
ahead = "[▴│[${count}](bold bright-cyan)│](bold italic green)"
behind = "[▿│[${count}](bold bright-cyan)│](bold italic red)"
diverged = "[◇ ▴┤[${ahead_count}](bold white)│▿┤[${behind_count}](bold white)│](bold italic bright-magenta)"
untracked = "[◌◦](bold bright-yellow)"
stashed = "[◃◈](bold bright-purple)"
modified = "[●◦](bold yellow)"
staged = "[▪┤[$count](bold bright-cyan)│](bold italic bright-cyan)"
renamed = "[◎◦](bold bright-magenta)"
deleted = "[✕](bold red)"

[deno]
format = " [deno](italic bright-purple) [∫ $version](bold bright-cyan)"
version_format = "${raw}"

[lua]
format = " [lua](italic bright-purple) [${symbol}${version}]($style)"
version_format = "${raw}"
symbol = "⨀ "
style = "bold bright-magenta"

[nodejs]
format = " [node](italic bright-purple) [◫ ($version)](bold bright-green)"
version_format = "${raw}"
detect_files = ["package-lock.json", "yarn.lock"]
detect_folders = ["node_modules"]
detect_extensions = []

[python]
format = " [py](italic bright-purple) [${symbol}${version}]($style)[ ($virtualenv)]($style)"
symbol = "[⌉](bold bright-cyan)⌊ "
version_format = "${raw}"
style = "bold bright-magenta"

[ruby]
format = " [rb](italic bright-purple) [${symbol}${version}]($style)"
symbol = "◆ "
version_format = "${raw}"
style = "bold bright-red"

[rust]
format = " [rs](italic bright-purple) [$symbol$version]($style)"
symbol = "⊃ "
version_format = "${raw}"
style = "bold bright-magenta"

[package]
format = " [pkg](italic bright-purple) [$symbol$version]($style)"
version_format = "${raw}"
symbol = "◨ "
style = "bold bright-cyan"

[swift]
format = " [sw](italic bright-purple) [${symbol}${version}]($style)"
symbol = "◁ "
style = "bold bright-magenta"
version_format = "${raw}"

[nix_shell]
style = 'bold italic bright-purple'
symbol = '✶'
format = '[$symbol nix⎪$state⎪]($style) [$name](italic bright-cyan)'
impure_msg = '[⌽](bold bright-red)'
pure_msg = '[⌾](bold bright-green)'
unknown_msg = '[◌](bold bright-yellow)'

[aws]
disabled = true

[buf]
symbol = "■ "
format = " [buf](italic bright-purple) [$symbol $version]($style)"
style = "bold bright-cyan"

[c]
symbol = "ℂ "
format = " [$symbol($version)]($style)"
style = "bold bright-cyan"

[conda]
symbol = "◯ "
format = " [conda](italic bright-purple) [$symbol$environment]($style)"
style = "bold bright-cyan"

[docker_context]
symbol = "◧ "
format = " [docker](italic bright-purple) [$symbol$context]($style)"
style = "bold bright-cyan"

[golang]
symbol = "∩ "
format = " [go](italic bright-purple) [$symbol($version)]($style)"
style = "bold bright-cyan"