[mgr]
show_hidden = true
sort_by = "natural"
sort_sensitive = false
sort_dir_first = true
linemode = "size"
show_symlink = true
ratio = [2, 2, 7]

[preview]
max_width = 1000
max_height = 1000
image_filter = "lanczos3"

[[plugin.prepend_fetchers]]
id = "git"
url = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
url = "*/"
run = "git"

[opener]
edit = [
  { run = 'nvim "$@"', block = true, for = "unix" },
]
open = [
  { run = 'xdg-open "$@"', desc = "Open", for = "unix" },
]

[open]
prepend_rules = [
  { mime = "text/*", use = "edit" },
  { mime = "application/json", use = "edit" },
  { name = "*.toml", use = "edit" },
  { name = "*.kdl", use = "edit" },
  { name = "*.conf", use = "edit" },
]
